config/routes.rb
Rails.application.routes.draw do
    # so we can see followers and following
    # results: localhost:3000/user/1/following -> shows all User1's following (who the follow)
    resources :users do
        member do
            get :following, :followers
    end
end
    resources :microposts, only: [:create, :destroy] # we are not able to create and delete microposts
    resources :sessions, only: [:new, :create, :destroy]
    resources :relationships, only: [:create, :destroy]
    root 'static_pages#home'

    # static pages
    get '/about', to: 'static_pages#about'
    get '/contact', to: 'static_pages#contact'
    # Users
    get '/signup', to:'users#new'
    # Login and logout index
    get '/login', to:'sessions#new'
    delete '/logout', to: 'sessions#destroy'
end

app/models/user.rb
class User < ApplicationRecord
  has_many :microposts, dependent: :destroy #If the user is deleted, the posts are also deleted.
  # fllowing function ===================================================
  #followed
  has_many :relationships, foreign_key: "follower_id", dependent: :destroy
  has_many :followed_users, through: :relationships, source: :followed # how you assign a nameto a relationship
  # followers
  has_many :reverse_relationships, foreign_key: "followed_id", dependent: :destroy, class_name: "Relationship"
  has_many :followers, through: :reverse_relationships, source: :follower # this is where you see your followers
  #======================================================================

  validates :name, presence: true
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true,
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  
  has_secure_password
  validates :password, length: { minimum: 6 }


  # making a function inside model means we are going to talkto the detabase
  def feed
    #sihntaro is ID #1
    # Micropost.where("user_id = id", #1)
    # meaning all of_shintaro7s posts about sush will show up
    # Micropost.where("user_id = ?", id)
    Micropost.from_users_followed_by(self) #this shows pasts from other users you followed
  end

  # this is where we make our working fllow methods
  # Follows a user
  def follow(other_user)
    relationships.create!(followed_id: other_user.id) # whoever we follow, we get their ID
    # current user is FLLOWER and the other user is FOLLOWED
  end

  # Unfollows a user 
  def unfollow(other_user)
    relationships.find_by(followed_id: other_user.id).destroy
  end

  #Returns true if the current user is folloeing the other user
  # this one is the same as logged_in? function
  def following?(other_user)
    relationships.find_by(followed_id: other_user.id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :only_loggedin_users, only: [:index, :edit, :update,
                                                            :destroy, :following, :followers]
  before_action :correct_user, only: [:edit, :update]


  def index
    # @users = User.all
    @users = User.paginate(page: params[:page], per_page: 5)
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to login_url
    else
      render 'new'
    end
  end

  def show
    @user = User.find(params[:id])
    #while showing the User's profile page,show all their microposts too 
    @microposts = @user.microposts.paginate(page: params[:page], per_page: 12)
  end



  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      redirect_to @user
    else
      render 'edit'
    end
  end

  def destroy
    User.find(params[:id]).destroy
    redirect_to users_url
  end

  # method and a assignment for our FOLLOWING page
  def following
    @title = "Following" #intead of using <% provide() %> ew can put title here
    @user = User.find(params[:id]) #get the user ID
    @users = @user.followed_users.paginate(page: params[:page], per_page: 10) #this is shows the following users
    @all_users = @user.followed_users #just assignment to get all the users you FOllOW
    render 'show_follow' # _show_follow.html.erb will show all the follow page
    # _show_follow.html.erb is a partial file for following and followers page
  end

  # method and an assignment for our followers page
  def followers
    @title = "Followers"
    @user = User.find(params[:id])
    @users = @user.followers.paginate(page: params[:page], per_page: 10)
    @all_users = @user.followers
    render 'show_follow'
  end


  private
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end


  # Before filters / before actions  -> A type of authorization


  def correct_user
    @user = User.find(params[:id])
    redirect_to(root_url) unless current_user?(@user)
  end
end

app/helpers/users_helper.rb
module UsersHelper
  # Returns the Gravatar (http://gravatar.com/) for the given user.
  def gravatar_for(user, options = { size: 50 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/users/_follow.html.erb
<%# this is the follow button %>
<%= form_for(current_user.relationships.build, remote: true) do |f| %>
<%# whenever we dlick the follow button, arelationship is created between 2 users %>
<%# remote: true means it will not need refresh after you click the button %>

<%# how to save an ID without text field/text area/password area %>
<div><%= hidden_field_tag :followed_id, @user.id %></div>
<%= f.submit "Follow", class: "btn btn-large btn-primary" %>
<% end %>

app/views/users/_follow_form.html.erb
<% unless current_user?(@user) %> <%# only logged_in and current_users are able to FOLLOW and UNFOLLOW %>
    <div id="follow_form">
        <% if current_user.following?(@user) %>
            <%= render 'unfollow'%>
        <% else %>
            <%= render 'follow' %>
        <% end %>
    </div>
<% end %>

app/views/users/_form.html.erb
<%= form_for @user do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name, class: "form-control" %>

    <%= f.label :email %>
    <%= f.text_field :email, class: "form-control"%>

    <%= f.label :password %>
    <%= f.password_field :password, class: "form-control"%>

    <%= f.label :password_confirmation, "confirmation" %>
    <%= f.password_field :password_confirmation, class: "form-control"%>

    <%= f.submit "Save changes", class: "btn btn-block btn-primary" %>

<% end %>

app/views/users/_unfollow.html.erb
<%= form_for((current_user.relationships).find_by(followed_id: @user.id),
                                                                method: :delete,
                                                                remote: true) do |f| %>
    <%= f.submit "Unfollow", class: "btn btn-large btn-danger" %>
<% end %>

app/views/users/_user.html.erb
<li class="col-12 my-4">
    <%= link_to gravatar_for(user), user %>
    <span class="user">
        <%= link_to user.name, user %>
    </span>
</li>

app/views/users/edit.html.erb
<% provide(:title, 'Edit Profile') %>
<div class="container form-edit">
    <h1 class="text-center">Edit your Profile</h1>
    <%= render 'form' %>
</div>

app/views/users/index.html.erb
<% provide(:title, 'Users') %>
<div class="container">
    <div class="jumbotron mt-4">
        <h1 class="text-center">List of Users</h1>
        　　 <%= will_paginate %>
                <ul class="users">
                    <% @users.each do |user| %>
                        <li>
                            <%= gravatar_for user, size: 52 %>
                            <%= link_to user.name, user %>
                            <%= link_to 'delete', user_path(user), method: :delete,
                                                        data: { confirm: "Are you sure?" } %>
                        </li>
                <% end %>
                </ul>
                <%= will_paginate%>
    </div>
</div>

app/views/users/new.html.erb
<% provide(:title, 'sign up') %>
<div class="container form-edit">
    <h1 class="text-center">Sign up</h1>
    <%= render 'form' %>
    <p>Already have an account? <%= link_to "Login", login_path %></p>
</div>
  

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="container">
    <div class="row show-gravatar">
        <section>
        <h1>
        
            <%= gravatar_for @user %>
            <%= @user.name %>
        
        <%# <%= render 'shared/user_info' %> 
        </h1>
        </section>
        <!-- show Microposts of specific user in their profile(porifle) page -->
        <div class="microposts-lists">
            <%= render 'follow_form' if logged_in?%>
            <% if @user.microposts.any? %>
                <h3 class="text-center">Microposts Feed</h3>
                <ol class="microposts-lists">
                    <%= render @microposts %> <!-- This will go to a partial file -->
                </ol>
                <div class="container">
                    <%= will_paginate @microposts %> <!-- @microposts connects to users_controller -->
                </div>
            <% end %>
        </div>
    </div>
</div>

app/views/users/show_follow.html.erb
<% provide(:title, @title) %>
<div class="row">
    <div class="col-4">
        <section class="user_info">
            <%= render 'shared/user_info' %>
        </section>
        <section class="stat">
            <%= render 'shared/stats' %>
            <!-- showing the profile pictures of all followers/following -->
            <% if @all_users.any? %>
                <div class="user_avatars">
                    <% @all_users.each do |user| %>
                        <%= link_to gravatar_for(user,size: 30), user %>
                    <% end %>
                </div>
            <% end %>
        </section>
    </div>
    <!-- this shows all your followers/following -->
    <div class="col-8">
        <h3><%= @title %></h3>
        <% if @users.any? %>
            <% @users.each do |user| %>
                <ul class="users follow">
                    <%= render user %>
                </ul>
               <% end %>
                <%= will_paginate %>
        <% end %>

    </div>
</div>