config/routes.rb
Rails.application.routes.draw do
    # so we can see followers and following
    # results: localhost:3000/user/1/following -> shows all User1's following (who the follow)
    resources :users do
        member do
            get :following, :followers
    end
end
    resources :microposts, only: [:create, :destroy] # we are not able to create and delete microposts
    resources :sessions, only: [:new, :create, :destroy]
    resources :relationships, only: [:create, :destroy]
    root 'static_pages#home'

    # static pages
    get '/about', to: 'static_pages#about'
    get '/contact', to: 'static_pages#contact'
    # Users
    get '/signup', to:'users#new'
    # Login and logout index
    get '/login', to:'sessions#new'
    delete '/logout', to: 'sessions#destroy'
end

app/views/layouts/_footer.html.erb
<div class="footer">
    <%# link_to "AwesomeBlog", "#", class:"footer1", id="logo " %>
        <div class="col-12 bg-dark">
            <div class="container">                    
                <div class="row">
                    <div class="col-4 my-3 text-left text-secondary">
                    © ︎All right reserved
                    </div>
                    <div class="col-8 my-3 text-right text-secondary">
                    <i class="fa fa-facebook-square"></i>
                    <i class="fa fa-twitter-square"></i>
                    <i class="fa fa-instagram"></i>
                    </div>
                </div>
            </div>    
        </div>   
</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg fixed-top navbar-dark bg-dark">
    <%= link_to "AwesomeBlog", "#", class:"navbar-brand brand", id: "logo" %>
    <div class="collapse navbar-collapse">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item">
                <%= link_to "Home", root_path, class: "nav-link" %>
            </li>
            <li class="nav-item">
                <%= link_to "About", about_path, class: "nav-link" %>
            </li>
            <% if logged_in? %>
               <li><%= link_to "Users", users_path, class: "nav-link" %></li>
               <li class="nav-item dropdown">
                    <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown">
                    <%= current_user.name %> <b class="caret"></b>
                    </a>
                    <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <li><%= link_to "profile", current_user, class: "dropdown-item" %></li>
                        <li><%= link_to "settings", edit_user_path(current_user), class: "dropdown-item" %></li>
                        <li class="divider"></li>
                        <li>
                            <%= link_to "Sign out", logout_path, method: :delete, class: "dropdown-item" %>
                        </li>
                    </ul>
                </li>
            <% else %>  
            <li class="nav-item">
                <%= link_to "Signup", signup_path, class: "nav-link" %>    
            </li>
             <li class="nav-item">
                <%= link_to "Login", login_path, class: "nav-link" %>
            </li>
            <% end %>
        </ul>
    </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %>Awesome Blog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    
  </head>

  <body>

   <%= render 'layouts/header' %>
  
      <%= yield %>
   
    <%= render 'layouts/footer' %>
  </body>
</html>